# Generated by Django 3.1.7 on 2021-04-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instr',
            name='materials',
            field=models.TextField(default='', verbose_name='Материалы'),
        ),
    ]
