# Generated by Django 3.1.7 on 2021-04-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepti', '0002_auto_20210405_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='anons',
            field=models.CharField(default='Краткое описание блюда', max_length=250, verbose_name='Краткое описание блюда'),
        ),
    ]
