# Generated by Django 3.1.7 on 2021-04-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepti', '0003_articles_anons'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='avtor',
            field=models.CharField(default='So Delicious', max_length=250, verbose_name='Автор рецепта'),
        ),
    ]
