# Generated by Django 3.1.7 on 2021-04-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepti', '0005_auto_20210407_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_predl', models.CharField(max_length=150, verbose_name='Название блюда')),
                ('category_predl', models.CharField(max_length=100, verbose_name='Категория')),
                ('history_predl', models.CharField(default='Италия', max_length=150, verbose_name='Страна происхождения:')),
                ('full_text_predl', models.TextField(verbose_name='Рецепт')),
                ('anons_predl', models.CharField(default='Краткое описание блюда', max_length=250, verbose_name='Краткое описание блюда')),
                ('kkal_predl', models.CharField(default='150 ккал', max_length=50, verbose_name='Калорийность:')),
                ('avtor_predl', models.CharField(default='So Delicious', max_length=250, verbose_name='Автор рецепта')),
                ('date_predl', models.DateField(verbose_name='Дата публикации')),
                ('image_predl', models.ImageField(upload_to='images/predl-recipes', verbose_name='Изображения')),
            ],
            options={
                'verbose_name': 'Предложенный рецепт',
                'verbose_name_plural': 'Предложеныне рецепты',
            },
        ),
    ]
