# Generated by Django 3.1.7 on 2021-04-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepti', '0006_predl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predl',
            options={'verbose_name': 'Предложенный рецепт', 'verbose_name_plural': 'Предложенные рецепты'},
        ),
        migrations.AlterField(
            model_name='predl',
            name='anons_predl',
            field=models.CharField(default='', max_length=250, verbose_name='Краткое описание блюда'),
        ),
        migrations.AlterField(
            model_name='predl',
            name='avtor_predl',
            field=models.CharField(default='', max_length=250, verbose_name='Автор рецепта'),
        ),
        migrations.AlterField(
            model_name='predl',
            name='history_predl',
            field=models.CharField(default='', max_length=150, verbose_name='Страна происхождения:'),
        ),
        migrations.AlterField(
            model_name='predl',
            name='kkal_predl',
            field=models.CharField(default='', max_length=50, verbose_name='Калорийность:'),
        ),
    ]
