# Generated by Django 3.1.7 on 2021-04-07 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepti', '0007_auto_20210407_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predl',
            name='date_predl',
        ),
        migrations.RemoveField(
            model_name='predl',
            name='image_predl',
        ),
    ]
